const CANVAS_WIDTH = 1200;
const CANVAS_HEIGHT = 300;

const DINO_WIDTH = 16;
const DINO_HEIGHT = 32;
const GRAVITY = 0.5;
const DINO_JUMP_POWER = 7;

const OBSTACLE_WIDTH = 16;
const OBSTACLE_HEIGHT = 16;
const OBSTACLE_SPEED = 2;

const OBSTACLE_MIN_DISTANCE = 100;
const OBSTACLE_MAX_DISTANCE = 500;